<?php
return [
    'tpbs.admin' => [
        'type' => 2,
        'description' => 'จัดการระบบ',
    ],
    'tpbs.admin.accesslog' => [
        'type' => 2,
        'description' => 'log การเข้าสู่ระบบ',
    ],
    'tpbs.admin.contentlog' => [
        'type' => 2,
        'description' => 'log การใช้งานข่าว',
    ],
    'tpbs.admin.user' => [
        'type' => 2,
        'description' => 'จัดการผู้ใช้งานระบบ',
    ],
    'tpbs.content' => [
        'type' => 2,
        'description' => 'เนื้อหา/ข่าว ',
    ],
    'tpbs.content.approve' => [
        'type' => 2,
        'description' => 'ตรวจสอบ Content ',
    ],
    'tpbs.content.draft' => [
        'type' => 2,
        'description' => 'ร่าง เนื้อหา/ข่าว ',
    ],
    'tpbs.content.edit' => [
        'type' => 2,
        'description' => 'แก้ใข หน้า Content',
    ],
    'tpbs.content.view' => [
        'type' => 2,
        'description' => 'ดู หน้า Content ',
    ],
    'tpbs.feed' => [
        'type' => 2,
        'description' => 'หัวข้อไทยพีบีเอสโฟกัส',
    ],
    'tpbs.feed.approve' => [
        'type' => 2,
        'description' => 'Public หัวข้อไทยพีบีเอสโฟกัส',
    ],
    'tpbs.feed.draft' => [
        'type' => 2,
        'description' => 'ร่าง หัวข้อไทยพีบีเอสโฟกัส',
    ],
    'tpbs.feed.edit' => [
        'type' => 2,
        'description' => 'แก้ใข หัวข้อไทยพีบีเอสโฟกัส',
    ],
    'tpbs.feedcontent' => [
        'type' => 2,
        'description' => 'เนื้อหาไทยพีบีเอสโฟกัส',
    ],
    'tpbs.feedcontent.approve' => [
        'type' => 2,
        'description' => 'Public เนื้อหาไทยพีบีเอสโฟกัส',
    ],
    'tpbs.feedcontent.draft' => [
        'type' => 2,
        'description' => 'ร่าง เนื้อหาไทยพีบีเอสโฟกัส',
    ],
    'tpbs.feedcontent.edit' => [
        'type' => 2,
        'description' => 'แก้ใข เนื้อหาไทยพีบีเอสโฟกัส',
    ],
    'tpbs.gallery' => [
        'type' => 2,
        'description' => 'แกลอรี่ (gallery)',
    ],
    'tpbs.gallery.approve' => [
        'type' => 2,
        'description' => 'Public แกลอรี่ ',
    ],
    'tpbs.gallery.draft' => [
        'type' => 2,
        'description' => 'ร่าง แกลอรี่ ',
    ],
    'tpbs.gallery.edit' => [
        'type' => 2,
        'description' => 'แก้ใข แกลอรี่ ',
    ],
    'tpbs.home' => [
        'type' => 2,
        'description' => 'หน้าหลัก',
    ],
    'tpbs.microsite' => [
        'type' => 2,
        'description' => 'ไมโครไซต์ (microsite)',
    ],
    'tpbs.microsite.edit' => [
        'type' => 2,
        'description' => 'จัดการแก้ใขไมโครไซต์ (microsite)',
    ],
    'tpbs.oil' => [
        'type' => 2,
        'description' => 'ราคานํ้ามัน',
    ],
    'tpbs.oil.edit' => [
        'type' => 2,
        'description' => 'แก้ใขราคานํ้ามัน',
    ],
    'tpbs.quote' => [
        'type' => 2,
        'description' => 'คำในข่าว (quote)',
    ],
    'tpbs.quote.approve' => [
        'type' => 2,
        'description' => 'Public คำในข่าว (quote)',
    ],
    'tpbs.quote.draft' => [
        'type' => 2,
        'description' => 'ร่าง คำในข่าว (quote)',
    ],
    'tpbs.quote.edit' => [
        'type' => 2,
        'description' => 'แก้ใข คำในข่าว (quote)',
    ],
    'tpbs.tag' => [
        'type' => 2,
        'description' => 'แท็กยอดฮิต (แท็กข่าว)',
    ],
    'tpbs.user' => [
        'type' => 2,
        'description' => 'ผู้ใช้งานระบบ',
    ],
    'tpbs.user.profile' => [
        'type' => 2,
        'description' => 'แก้ใขข้อมูลส่วนตัว',
    ],
    'tpbs.weather' => [
        'type' => 2,
        'description' => 'พยากรณ์อากาศ (weather)',
    ],
    'tpbs.weather.approve' => [
        'type' => 2,
        'description' => 'Public พยากรณ์อากาศ (weather)',
    ],
    'tpbs.weather.draft' => [
        'type' => 2,
        'description' => 'ร่าง พยากรณ์อากาศ (weather)',
    ],
    'tpbs.weather.edit' => [
        'type' => 2,
        'description' => 'แก้ใข พยากรณ์อากาศ (weather)',
    ],
    'tpbs.web' => [
        'type' => 2,
        'description' => 'การจัดการเวบ (web)',
    ],
    'tpbs.web.crime' => [
        'type' => 2,
        'description' => 'จัดการข่าวอาชญากรรม',
    ],
    'tpbs.web.crime.edit' => [
        'type' => 2,
        'description' => 'แก้ใขการจัดการข่าวอาชญากรรม',
    ],
    'tpbs.web.eco' => [
        'type' => 2,
        'description' => 'จัดการข่าวเศรษฐกิจ',
    ],
    'tpbs.web.eco.edit' => [
        'type' => 2,
        'description' => 'แก้ใขการจัดการข่าวเศรษฐกิจ',
    ],
    'tpbs.web.ent' => [
        'type' => 2,
        'description' => 'จัดการข่าวศิลปบันเทิง',
    ],
    'tpbs.web.ent.edit' => [
        'type' => 2,
        'description' => 'แก้ใขการจัดการข่าวศิลปบันเทิง',
    ],
    'tpbs.web.home' => [
        'type' => 2,
        'description' => 'จัดการหน้าแรก',
    ],
    'tpbs.web.home.edit' => [
        'type' => 2,
        'description' => 'แก้ใขการจัดการหน้าแรก',
    ],
    'tpbs.web.homenews' => [
        'type' => 2,
        'description' => 'จัดการข่าวหน้าแรก',
    ],
    'tpbs.web.homenews.edit' => [
        'type' => 2,
        'description' => 'แก้ใขการจัดการข่าวหน้าแรก',
    ],
    'tpbs.web.oversea' => [
        'type' => 2,
        'description' => 'จัดการข่าวต่างประเทศ',
    ],
    'tpbs.web.oversea.edit' => [
        'type' => 2,
        'description' => 'แก้ใขการจัดการข่าวต่างประเทศ',
    ],
    'tpbs.web.pol' => [
        'type' => 2,
        'description' => 'จัดการข่าวการเมือง',
    ],
    'tpbs.web.pol.edit' => [
        'type' => 2,
        'description' => 'แก้ใขการจัดการข่าวการเมือง',
    ],
    'tpbs.web.provincial' => [
        'type' => 2,
        'description' => 'จัดการข่าวภูมิภาค',
    ],
    'tpbs.web.provincial.edit' => [
        'type' => 2,
        'description' => 'แก้ใขการจัดการข่าวภูมิภาค',
    ],
    'tpbs.web.social' => [
        'type' => 2,
        'description' => 'จัดการข่าวสังคม',
    ],
    'tpbs.web.social.edit' => [
        'type' => 2,
        'description' => 'แก้ใขการจัดการข่าวสังคม',
    ],
    'tpbs.web.sport' => [
        'type' => 2,
        'description' => 'จัดการข่าวกีฬา',
    ],
    'tpbs.web.sport.edit' => [
        'type' => 2,
        'description' => 'แก้ใขการจัดการข่าวกีฬา',
    ],
    'tpbs.widget' => [
        'type' => 2,
        'description' => 'ข้อมูลกำหนดเอง (widget)',
    ],
    'tpbs.widget.approve' => [
        'type' => 2,
        'description' => 'Public ข้อมูลกำหนดเอง (widget)',
    ],
    'tpbs.widget.draft' => [
        'type' => 2,
        'description' => 'ร่าง ข้อมูลกำหนดเอง (widget)',
    ],
    'tpbs.widget.edit' => [
        'type' => 2,
        'description' => 'แก้ใข ข้อมูลกำหนดเอง (widget)',
    ],
    'tpbs.role.admin' => [
        'type' => 1,
        'description' => 'ผู้ดูแลระบบ',
        'children' => [
            'tpbs.admin',
            'tpbs.admin.accesslog',
            'tpbs.admin.contentlog',
            'tpbs.admin.user',
            'tpbs.content',
            'tpbs.content.approve',
            'tpbs.content.draft',
            'tpbs.content.edit',
            'tpbs.content.view',
            'tpbs.feed',
            'tpbs.feed.approve',
            'tpbs.feed.draft',
            'tpbs.feed.edit',
            'tpbs.feedcontent',
            'tpbs.feedcontent.approve',
            'tpbs.feedcontent.draft',
            'tpbs.feedcontent.edit',
            'tpbs.gallery',
            'tpbs.gallery.approve',
            'tpbs.gallery.draft',
            'tpbs.gallery.edit',
            'tpbs.home',
            'tpbs.microsite',
            'tpbs.microsite.edit',
            'tpbs.oil',
            'tpbs.oil.edit',
            'tpbs.quote',
            'tpbs.quote.approve',
            'tpbs.quote.draft',
            'tpbs.quote.edit',
            'tpbs.tag',
            'tpbs.user',
            'tpbs.user.profile',
            'tpbs.weather',
            'tpbs.weather.approve',
            'tpbs.weather.draft',
            'tpbs.weather.edit',
            'tpbs.web',
            'tpbs.web.crime',
            'tpbs.web.crime.edit',
            'tpbs.web.eco',
            'tpbs.web.eco.edit',
            'tpbs.web.ent',
            'tpbs.web.ent.edit',
            'tpbs.web.home',
            'tpbs.web.home.edit',
            'tpbs.web.homenews',
            'tpbs.web.homenews.edit',
            'tpbs.web.oversea',
            'tpbs.web.oversea.edit',
            'tpbs.web.pol',
            'tpbs.web.pol.edit',
            'tpbs.web.provincial',
            'tpbs.web.provincial.edit',
            'tpbs.web.social',
            'tpbs.web.social.edit',
            'tpbs.web.sport',
            'tpbs.web.sport.edit',
            'tpbs.widget',
            'tpbs.widget.approve',
            'tpbs.widget.draft',
            'tpbs.widget.edit',
        ],
    ],
    'tpbs.role.editor' => [
        'type' => 1,
        'description' => 'บรรณาธิการ',
        'children' => [
            'tpbs.content',
            'tpbs.content.approve',
            'tpbs.content.draft',
            'tpbs.content.edit',
            'tpbs.content.view',
            'tpbs.feed',
            'tpbs.feed.approve',
            'tpbs.feed.draft',
            'tpbs.feed.edit',
            'tpbs.feedcontent',
            'tpbs.feedcontent.approve',
            'tpbs.feedcontent.draft',
            'tpbs.feedcontent.edit',
            'tpbs.gallery',
            'tpbs.gallery.approve',
            'tpbs.gallery.draft',
            'tpbs.gallery.edit',
            'tpbs.home',
            'tpbs.microsite',
            'tpbs.microsite.edit',
            'tpbs.oil',
            'tpbs.oil.edit',
            'tpbs.quote',
            'tpbs.quote.approve',
            'tpbs.quote.draft',
            'tpbs.quote.edit',
            'tpbs.tag',
            'tpbs.user',
            'tpbs.user.profile',
            'tpbs.weather',
            'tpbs.weather.approve',
            'tpbs.weather.draft',
            'tpbs.weather.edit',
            'tpbs.web',
            'tpbs.web.crime',
            'tpbs.web.crime.edit',
            'tpbs.web.eco',
            'tpbs.web.eco.edit',
            'tpbs.web.ent',
            'tpbs.web.ent.edit',
            'tpbs.web.home',
            'tpbs.web.home.edit',
            'tpbs.web.homenews',
            'tpbs.web.homenews.edit',
            'tpbs.web.oversea',
            'tpbs.web.oversea.edit',
            'tpbs.web.pol',
            'tpbs.web.pol.edit',
            'tpbs.web.provincial',
            'tpbs.web.provincial.edit',
            'tpbs.web.social',
            'tpbs.web.social.edit',
            'tpbs.web.sport',
            'tpbs.web.sport.edit',
            'tpbs.widget',
            'tpbs.widget.approve',
            'tpbs.widget.draft',
            'tpbs.widget.edit',
        ],
    ],
    'tpbs.role.journalist' => [
        'type' => 1,
        'description' => 'นักข่าว',
        'children' => [
            'tpbs.content',
            'tpbs.content.draft',
            'tpbs.content.edit',
            'tpbs.content.view',
            'tpbs.feed',
            'tpbs.feed.draft',
            'tpbs.feed.edit',
            'tpbs.feedcontent',
            'tpbs.feedcontent.draft',
            'tpbs.feedcontent.edit',
            'tpbs.gallery',
            'tpbs.gallery.draft',
            'tpbs.gallery.edit',
            'tpbs.home',
            'tpbs.microsite',
            'tpbs.microsite.edit',
            'tpbs.oil',
            'tpbs.oil.edit',
            'tpbs.quote',
            'tpbs.quote.draft',
            'tpbs.quote.edit',
            'tpbs.tag',
            'tpbs.weather',
            'tpbs.weather.approve',
            'tpbs.weather.draft',
            'tpbs.weather.edit',
            'tpbs.web',
            'tpbs.web.crime',
            'tpbs.web.crime.edit',
            'tpbs.web.eco',
            'tpbs.web.eco.edit',
            'tpbs.web.ent',
            'tpbs.web.ent.edit',
            'tpbs.web.home',
            'tpbs.web.home.edit',
            'tpbs.web.homenews',
            'tpbs.web.homenews.edit',
            'tpbs.web.oversea',
            'tpbs.web.oversea.edit',
            'tpbs.web.pol',
            'tpbs.web.pol.edit',
            'tpbs.web.provincial',
            'tpbs.web.provincial.edit',
            'tpbs.web.social',
            'tpbs.web.social.edit',
            'tpbs.web.sport',
            'tpbs.web.sport.edit',
            'tpbs.widget',
            'tpbs.widget.draft',
            'tpbs.widget.edit',
        ],
    ],
];
